/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLolRouteImport } from './routes/admin-lol'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as AdminLolIndexRouteImport } from './routes/admin-lol.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as AdminLolSettingsRouteImport } from './routes/admin-lol.settings'
import { Route as AdminLolProductsRouteImport } from './routes/admin-lol.products'
import { Route as AdminLolOrdersRouteImport } from './routes/admin-lol.orders'

const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLolRoute = AdminLolRouteImport.update({
  id: '/admin-lol',
  path: '/admin-lol',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLolIndexRoute = AdminLolIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLolRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLolSettingsRoute = AdminLolSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminLolRoute,
} as any)
const AdminLolProductsRoute = AdminLolProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminLolRoute,
} as any)
const AdminLolOrdersRoute = AdminLolOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminLolRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin-lol': typeof AdminLolRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/lookbook': typeof LookbookRoute
  '/admin-lol/orders': typeof AdminLolOrdersRoute
  '/admin-lol/products': typeof AdminLolProductsRoute
  '/admin-lol/settings': typeof AdminLolSettingsRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin-lol/': typeof AdminLolIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/lookbook': typeof LookbookRoute
  '/admin-lol/orders': typeof AdminLolOrdersRoute
  '/admin-lol/products': typeof AdminLolProductsRoute
  '/admin-lol/settings': typeof AdminLolSettingsRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin-lol': typeof AdminLolIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin-lol': typeof AdminLolRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/lookbook': typeof LookbookRoute
  '/admin-lol/orders': typeof AdminLolOrdersRoute
  '/admin-lol/products': typeof AdminLolProductsRoute
  '/admin-lol/settings': typeof AdminLolSettingsRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin-lol/': typeof AdminLolIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin-lol'
    | '/auth'
    | '/checkout'
    | '/contact'
    | '/lookbook'
    | '/admin-lol/orders'
    | '/admin-lol/products'
    | '/admin-lol/settings'
    | '/shop/$slug'
    | '/admin-lol/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/checkout'
    | '/contact'
    | '/lookbook'
    | '/admin-lol/orders'
    | '/admin-lol/products'
    | '/admin-lol/settings'
    | '/shop/$slug'
    | '/admin-lol'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin-lol'
    | '/auth'
    | '/checkout'
    | '/contact'
    | '/lookbook'
    | '/admin-lol/orders'
    | '/admin-lol/products'
    | '/admin-lol/settings'
    | '/shop/$slug'
    | '/admin-lol/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminLolRoute: typeof AdminLolRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  LookbookRoute: typeof LookbookRoute
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-lol': {
      id: '/admin-lol'
      path: '/admin-lol'
      fullPath: '/admin-lol'
      preLoaderRoute: typeof AdminLolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-lol/': {
      id: '/admin-lol/'
      path: '/'
      fullPath: '/admin-lol/'
      preLoaderRoute: typeof AdminLolIndexRouteImport
      parentRoute: typeof AdminLolRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-lol/settings': {
      id: '/admin-lol/settings'
      path: '/settings'
      fullPath: '/admin-lol/settings'
      preLoaderRoute: typeof AdminLolSettingsRouteImport
      parentRoute: typeof AdminLolRoute
    }
    '/admin-lol/products': {
      id: '/admin-lol/products'
      path: '/products'
      fullPath: '/admin-lol/products'
      preLoaderRoute: typeof AdminLolProductsRouteImport
      parentRoute: typeof AdminLolRoute
    }
    '/admin-lol/orders': {
      id: '/admin-lol/orders'
      path: '/orders'
      fullPath: '/admin-lol/orders'
      preLoaderRoute: typeof AdminLolOrdersRouteImport
      parentRoute: typeof AdminLolRoute
    }
  }
}

interface AdminLolRouteChildren {
  AdminLolOrdersRoute: typeof AdminLolOrdersRoute
  AdminLolProductsRoute: typeof AdminLolProductsRoute
  AdminLolSettingsRoute: typeof AdminLolSettingsRoute
  AdminLolIndexRoute: typeof AdminLolIndexRoute
}

const AdminLolRouteChildren: AdminLolRouteChildren = {
  AdminLolOrdersRoute: AdminLolOrdersRoute,
  AdminLolProductsRoute: AdminLolProductsRoute,
  AdminLolSettingsRoute: AdminLolSettingsRoute,
  AdminLolIndexRoute: AdminLolIndexRoute,
}

const AdminLolRouteWithChildren = AdminLolRoute._addFileChildren(
  AdminLolRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminLolRoute: AdminLolRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  LookbookRoute: LookbookRoute,
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
